FROM node:18-alpine
WORKDIR /app
COPY . .
RUN pnpm install -w --frozen-lockfile
WORKDIR /app/packages/frontend
RUN pnpm build
EXPOSE 3000
RUN pnpm --filter ./packages/frontend preview --port 3000 --host
CMD ["pnpm","--filter","./packages/frontend","preview","--port","3000","--host"]
